version: '3'

services:
  slack-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack-bot
    volumes:
      - .:/app
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
    restart: unless-stopped
    ports:
      - "8080:8080"